### ISSUE TITLE
Remove HTTP/2 support until Go 1.6

### ISSUE THREAD

**Issue by foresmac** [vokal/vip#122]
The current use of the `github.com/bradfitz/http2` package to support HTTP/2 causes random and difficult to troubleshoot issues with iOS clients. We should remove this support until Go [officially supports it in 1.6](http://blog.golang.org/6years) slated for "early 2016":
> Early next year we will release more improvements in Go 1.6, including an SSA-based optimizing compiler back end, **HTTP/2 support for net/http servers and clients**, an official package vendoring mechanism, support for blocks in text and HTML templates, a memory sanitizer that checks both Go and C/C++ code, and the usual assortment of other improvements and fixes.

(emphasis mine)

**Comment by scottferg** [comment]
Or just try rebuilding it against 1.6. Very few Vip builds have gone out that weren't using Go tip.

**Comment by foresmac** [comment]
Now building on Go 1.6 in #128
