### ISSUE TITLE
Center crop even when resize isn't needed

### ISSUE THREAD

**Issue by jrit** [vokal/vip#96]
Right now, with a request like `s=200&c=true` if the image is 180x90 there is no transform. I think it would be better if even when scaling isn't needed, if center-crop is true, that the cropping is just performed at the full image size. Right now it causes layout issues where square images are expected and they may not be just because the file dimensions are small.

@scottferg @foresmac agree?

**Comment by rachelhyman** [comment]
I went to go open an issue like this and saw it already existed. Just seconding that it would be nice to be able to center-crop even when a size query parameter isn't specified. When I have a sec I'd like to open a PR so it's clearer in the documentation that at present, center-cropping will *not* work without a size parameter.

@foresmac @scottferg @jrit

**Comment by jrit** [comment]
@foresmac did I fix this on your now non-existent fork? Where did all the forks go?

**Comment by foresmac** [comment]
Ok, I see. This was technically meant to address a different issue that I think @jrit already fixed, but I agree that if `c=true` and there is no `s=xxx` param, that we can just give that option to vips and I think it would just work. (or at least it should.)

I also think that this probably could be solved by using https://github.com/h2non/bimg

**Comment by foresmac** [comment]
@jrit Possibly that is so. That particular branch only lives in my repo, and I still have it. I've been talking to @projectweekend to get a little time to address some (or all!) of the open issues by updating `libvips` and move to a [different Go binding](https://github.com/h2non/bimg) for it, as well as updating to Go 1.5 to fix the issue with reading CMYK JPEGs.

**Comment by jrit** [comment]
Let me know if you need anything, I'm 95% sure the crop handling is already in your media-proxy branch. I could maybe cherry pick out of my fork into master as well, if that won't get in your way.

**Comment by foresmac** [comment]
Oh, it looks like when @scottferg made vip public, it converted my fork into a private repo on my own account. Nuts. I'm sure there's a way to get it back up without losing anything, though.

**Comment by scottferg** [comment]
Just flip it public. That alternative libvips binding is the bees knees.

**Comment by foresmac** [comment]
I fixed it. I'm going to put in @jrit's fix for now and open a pull request to get it into mainline. I'll defer a better solution until I can use `bimg`.

@rachelhyman Whoever is responsible for Systems on your project should be able to update the version running for your project, but if not let me know and I'll try to get it updated ASAP.
